In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#headers = {
#  "User-Agent":
#  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582"
#}
headers = {'User-Agent': 'Mozilla/5.0'}
list_rumah = []
column_name = ['judul', 'lokasi', 'harga', 'luas_tanah_m2', 'luas_bangunan_m2', 'kamar_tidur', 'kamar_mandi', 'garasi', 'poster', 'posting_date']
kota = ['jakarta-selatan', 'jakarta-barat', 'jakarta-pusat', 'jakarta-timur', 'jakarta-utara', 'bogor', 'depok', 'tangerang', 'tangerang-selatan', 'bekasi']
index = 0

In [3]:
while index < len(kota):
    page = 1
    while page != 11:
        url = f"https://www.rumah123.com/jual/{kota[index]}/rumah/?page={page}"
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.content, 'html.parser')
        lists = soup.find_all('div', class_='ui-organisms-card-r123-featured__content-wrapper')
        #print(url)
        
        for list in lists:
            
            judul = list.find('h2')
            if judul is not None: 
                judul = list.find('h2').text.strip()
            else: judul = ''
                
            tag_p = list.find_all('p')
            
            lokasi = tag_p[0]
            if lokasi is not None:
                lokasi = tag_p[0].text.strip()
            else: lokasi = ''
        
            harga = list.find('strong').text.strip()
            if harga is not None:
                harga = list.find('strong').text.strip().replace('Rp ', '')
            else: harga = ''
        
            lt_lb = list.find_all('span', class_='attribute-value')
    
            try:
                luas_tanah = lt_lb[0]
                if luas_tanah is not None:
                    luas_tanah = lt_lb[0].text.strip().replace(' m\u00b2', '')
                else: luas_tanah = ''
            except IndexError:
                luas_tanah = ''
        
            try:
                luas_bangunan = lt_lb[1]
                if luas_bangunan is not None:
                    luas_bangunan = lt_lb[1].text.strip().replace(' m\u00b2', '')
                else: luas_bangunan = ''
            except IndexError:
                luas_bangunan = ''
        
            kt_km_g = list.find_all('span', class_='attribute-text')
    
            try:
                kamar_tidur = kt_km_g[0]
                if kamar_tidur is not None:
                    kamar_tidur = kt_km_g[0].text.strip()
                else: kamar_tidur = ''
            except IndexError:
                kamar_tidur = ''    
        
        
            try:
                kamar_mandi = kt_km_g[1]
                if kamar_mandi is not None:
                    kamar_mandi = kt_km_g[1].text.strip()
                else: kamar_mandi = ''
            except IndexError:
                kamar_mandi = ''
            
            try:
                garasi = kt_km_g[2]
                if garasi is not None:
                    garasi = kt_km_g[2].text.strip()
                else: garasi = ''
            except IndexError:
                garasi = ''
            
            try:
                poster = tag_p[2]
                if poster is not None:
                    poster = tag_p[2].text.strip()
                else: poster = ''
            except IndexError:
                poster = ''
            
            try:
                posting_date = tag_p[3]
                if posting_date is not None:
                    posting_date = tag_p[3].text.strip().replace('Tayang Sejak ', '').replace(',', '')
                else: posting_date = ''
            except IndexError:
                posting_date = ''
                                        
            info_rumah = [judul, lokasi, harga, luas_tanah, luas_bangunan, kamar_tidur, kamar_mandi, garasi, poster, posting_date]
            list_rumah.append(info_rumah)
            
        page = page + 1
    index += 1
    
df_rumah = pd.DataFrame(list_rumah, columns=column_name)
df_rumah

,judul,lokasi,harga,luas_tanah_m2,luas_bangunan_m2,kamar_tidur,kamar_mandi,garasi,poster,posting_date
0,Rumah Termurah Mewah Swimming Pool Turun Dari ...,"Kemang, Jakarta Selatan","7,8 Miliar",320,390,4,5,2,PIrman,01 September 2022
1,PONDOK INDAH Murah Sekali Lokasi Bagus,"Pondok Indah, Jakarta Selatan",15 Miliar,250,400,5,4,,yudhi ferdiansyah,31 Agustus 2022
2,Rumah Bagus @Dukuh Patra Kuningan Jakarta Selatan,"Kuningan, Jakarta Selatan",28 Miliar,502,650,4,4,,yudhi ferdiansyah,31 Agustus 2022
3,Rumah Baru Classic Minimalis Dalam Townhouse D...,"Pejaten, Jakarta Selatan","4,4 Miliar",165,180,4,3,2,Graha,31 Agustus 2022
4,Rumah Dijual di Sektor Premium Pondok Indah,"Pondok Indah, Jakarta Selatan","16,5 Miliar",388,450,6,4,,Yovanna Janus D,31 Agustus 2022
...,...,...,...,...,...,...,...,...,...,...
1942,Rumah cantik asri & nyaman di Jati asih 15 men...,"Jatibening, Bekasi",740 Juta,64,70,3,2,2,Moh Mufti,14 Agustus 2022
1943,Cluster 2 lantai harga 1 lantai di jati asih J...,"Jatiwarna, Bekasi",627 Juta,61,60,3,2,2,Moh Mufti,14 Agustus 2022
1944,Hny 3 menit ke Tol Jatiwarna Rumah BAGUS MURAH...,"Jatiwarna, Bekasi","1,29 Miliar",90,130,5,3,2,Eti Kurniawati,07 Agustus 2022
1945,Rumah BAGUS MURAH perumahn STRATEGIS 3 ment ke...,"Jatiwarna, Bekasi","1,29 Miliar",90,130,5,3,2,Eti Kurniawati,07 Agustus 2022
1946,Rumah Murah Jalan Lebar Lepas Cepat Cluster Ar...,"Harapan Indah, Bekasi","1,4 Miliar",144,100,3,2,1,Darto,27 Agustus 2022

In [4]:
df_rumah.to_csv('harga_rumah_jabodetabek.csv', index=False)
df_rumah.tail()

,judul,lokasi,harga,luas_tanah_m2,luas_bangunan_m2,kamar_tidur,kamar_mandi,garasi,poster,posting_date
1942,Rumah cantik asri & nyaman di Jati asih 15 men...,"Jatibening, Bekasi",740 Juta,64,70,3,2,2,Moh Mufti,14 Agustus 2022
1943,Cluster 2 lantai harga 1 lantai di jati asih J...,"Jatiwarna, Bekasi",627 Juta,61,60,3,2,2,Moh Mufti,14 Agustus 2022
1944,Hny 3 menit ke Tol Jatiwarna Rumah BAGUS MURAH...,"Jatiwarna, Bekasi","1,29 Miliar",90,130,5,3,2,Eti Kurniawati,07 Agustus 2022
1945,Rumah BAGUS MURAH perumahn STRATEGIS 3 ment ke...,"Jatiwarna, Bekasi","1,29 Miliar",90,130,5,3,2,Eti Kurniawati,07 Agustus 2022
1946,Rumah Murah Jalan Lebar Lepas Cepat Cluster Ar...,"Harapan Indah, Bekasi","1,4 Miliar",144,100,3,2,1,Darto,27 Agustus 2022